pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
include ':app', ':core'

if (file('local.gradle').exists()) {
    apply from: 'local.gradle'
}
